# Generated by Django 4.2 on 2023-04-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boardgames", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="boardgame", name="difficulty_level",),
        migrations.RemoveField(model_name="boardgame", name="max_players",),
        migrations.RemoveField(model_name="boardgame", name="min_players",),
        migrations.RemoveField(model_name="boardgame", name="playtime",),
    ]
