# Generated by Django 4.2 on 2023-04-19 07:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boardgames", "0002_remove_boardgame_difficulty_level_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="GameLoan", new_name="Loan",),
    ]
