# Generated by Django 4.2 on 2023-04-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0005_remove_boardgame_status_boardgame_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='age_range',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
