# Generated by Django 4.2 on 2023-04-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0006_boardgame_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Is returned'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='is_available',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Borrowed')], default=True, verbose_name='Is Available'),
        ),
    ]
