# Generated by Django 4.2 on 2023-04-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0007_loan_is_returned_alter_boardgame_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['is_available', '-date_modified', '-date_created']},
        ),
    ]
